# docker-compose

# the docker-compose is for information purpose only
# the file maintains a 2-Space for TAB (instead of 4)
# which is the default for all other file(s)

version: "3.8"

services:

  database:

    image: mysql:8.0.26

    container_name: backend

    ports:
      # MySQL by default runs on 3306
      # the host is mapped to 33061 from host machine
      - "33061:3306"

    expose:
      - "3306" # expose MySQL-Client

    environment:
      # using root for mysql-client
      # https://github.com/docker-library/mysql
      MYSQL_USER: pOrgz
      MYSQL_PASSWORD: myAdmin
      MYSQL_ROOT_PASSWORD: admin
      # note you can create a new database using MYSQL_DATABASE
      # but, only single database can be created by the same
      # https://stackoverflow.com/a/40336552/6623589
      # or, you can create multiple database from init file
      MYSQL_DATABASE: financials_dev

    # volumes:
      # add, persistent storage (if required)
      # More Information : https://stackoverflow.com/a/67558967/6623589
      # mount the schema file with docker-entrypoint
      # - ./assets/db/init.sql:/docker-entrypoint-initdb.d/SCHEMA.sql

  standalone:

    image: mysql:5.7

    container_name: mail-server

    # using hMailServer for testing email services
    # https://www.hmailserver.com/
    # the application is available ONLY for MySQL=5.7

    ports:
      - "33062:3306"

    environment:
      # database is created by hMailServer
      MYSQL_ROOT_PASSWORD: admin
