# dummy database and file for oauth application testing
version: "3.8"

services:

  database:

    image: mysql:8.0.26 # use the specified version, or use latest

    container_name: oauth-dummy-2

    ports:
      - "33061:3306" # default mapped port to 33061, change as required
    
    volumes: # specify files/directory to map
      - ./assets/test_database.sql:/tmp/pOrgz/oauth/test_database.sql
    
    command: # initialize database with dummy data
      --init-file /tmp/pOrgz/oauth/test_database.sql

    environment: # using root as default
      # note you can create a new database using MYSQL_DATABASE
      # but, only single database can be created by the same
      # https://stackoverflow.com/a/40336552/6623589
      # using test file to create database, and populate tables and data
      MYSQL_ROOT_USER:     root
      MYSQL_ROOT_PASSWORD: admin
