/********************************************************************
DBML - Database Markup Language for ERD & Documentation

DBML is an unique language developed by the Holistics Software INC.
(https://www.holistics.io/) designed to define and document database
structures and schema (https://dbml.dbdiagram.io/home).

The project schema and usages are described under the `project` tag
which supports markdown syntax when the document is hosted using
https://dbdocs.io/ website.
********************************************************************/

project finfolio {
  database_type: 'PostgreSQL'
  document_name: 'Finace Portfolio Schema'
}

// ! METADATA Namespace - Configuration & Settings
table meta.account_type_detail {
  account_type_id char(3) [pk, not null]

  // typically the additional column are for end user (internal)
  account_type_name varchar(32)  [unique, not null]
  account_type_desc varchar(128) [unique, not null]
}

table meta.account_subtype_detail {
  account_subtype_id char(3) [pk, not null]
  account_type_id    char(3) [not null, ref: > meta.account_type_detail.account_type_id]

  // typically the additional column are for end user (internal)
  account_subtype_name varchar(32) [unique, not null,]
  account_subtype_desc varchar(64) [unique]
}


table meta.transaction_method {
  method_name varchar(7)  [pk, not null]
  method_desc varchar(64) [unique, not null]
}


table meta.expense_category {
  expense_category_name varchar(16) [pk, not null]
  expense_category_desc varchar(72) [unique, not null]
}


table meta.expense_subcategory {
  expense_subcategory_name varchar(48) [pk, not null]
  primary_expense_category varchar(16) [not null, ref: > meta.expense_category.expense_category_name]
  expense_subcategory_desc varchar(96) [unique, not null]
}


table meta.income_category {
  income_category_name varchar(16) [pk, not null]
  income_category_desc varchar(72) [unique, not null]
}


table meta.income_subcategory {
  income_subcategory_name varchar(48) [pk, not null]
  primary_income_category varchar(16) [not null, ref: > meta.expense_category.expense_category_name]
  income_subcategory_desc varchar(96) [unique, not null]
}


// ! PUBLIC Namespace - Using the default schema of PostgreSQL to hold user's essential informations
table public.user_account_detail {
  username varchar(16) [pk, not null]
  fullname varchar(64) [unique, not null]

  // good to have features, but not required to be maintained
  email varchar(128) [unique]
  phone varchar(16)  [unique]

  // date of birth is crucial for certain calculations/projections
  date_of_birth date

  // the user role and subrole is controlled externally to group
  user_role meta.user_role
}


table public.ledger_account_detail {
  // ? using randomly generated keys for account id
  // however, other end user may change the same as per need
  ledger_account_id char(5) [pk, not null]

  // the following information is for identification by end user
  account_name  varchar(64) [unique, not null]
  account_owner varchar(16) [not null, ref: > public.user_account_detail.username]

  // the type of account has a significant impact on end calculation
  account_type_id    char(3) [unique, not null, ref: > meta.account_type_detail.account_type_id]
  account_subtype_id char(3) [ref: > meta.account_subtype_detail.account_subtype_id]

  // ? account opening and closing information for future reference
  account_opened_on date [not null]
  account_closed_on date

  // an account may also be set as inactive even if the account is not closed
  account_marked_inactive_on date

  // ? we may not have all the transactions, thus we can set an opening balance
  opening_balance             numeric(12, 2) [not null, default: 0.00]
  opening_balance_recorded_on date           [not null] // default `account_opened_on`
}
