# using a YAML File for configuring `loggers`
# https://gist.github.com/kingspp/9451566a5555fb022215ca2b7b802f19

version : 1
disable_existing_loggers : false # https://docs.python.org/3/library/logging.config.html

formatters :

  standard :
    format : "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  extended :
    format : "%(asctime)s - %(name)s - %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"

filters:
# https://stackoverflow.com/a/62934150/6623589
  NoConsoleFilter:
    (): skeleton.NoConsoleFilter

handlers : # https://docs.python.org/3/library/logging.handlers.html#module-logging.handlers

  console : # standard, print(s) in console
    class     : logging.StreamHandler # equivalent to `from logging import StreamHandler`
    level     : NOTSET
    formatter : standard
    stream    : ext://sys.stdout
    filters   : [NoConsoleFilter]

  fileHandler :
    class       : logging.handlers.RotatingFileHandler
    level       : INFO
    formatter   : extended
    maxBytes    : 10485760 # 10MB
    backupCount : 20
    encoding    : utf8

root : # root logger, access by logging.getLogger(__name__)

  handlers  : [console, fileHandler]
  propogate : no
