CREATE TABLE IF NOT EXISTS "mwSymbolDetails" (
    ISINCode VARCHAR(12) PRIMARY KEY,
    SecurityName VARCHAR(256) UNIQUE NOT NULL,
    BSECODE VARCHAR(16) UNIQUE NOT NULL,
    NSESYMBOL VARCHAR(32) UNIQUE NOT NULL
);
